# This is a basic workflow that is manually triggered

name: Check and request builds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./check_latest.py "${{ secrets.BUILDER }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if ! git diff-index --quiet HEAD; then
          git commit -m "Build Requested"
          git push
          fi
